#pragma once

namespace sonic::protocol_defs {

// forward declaration of CommandCode
// The CommandCode implementation should be deduced from the command code python enum
// And be generated by the transpiler
enum class CommandCode;

}