from enum import unique
from sonic_protocol.schema import IEFieldName

@unique
class BaseFieldName(IEFieldName):
    UNDEFINED = 0
    COMMAND_CODE = 1
    
    ERROR_MESSAGE = 2
    MESSAGE = 3

    UNKNOWN_ANSWER = 4
    SUCCESS = 5


@unique
class EFieldName(IEFieldName):
    UNDEFINED = BaseFieldName.UNDEFINED.value
    COMMAND_CODE = BaseFieldName.COMMAND_CODE.value
    
    ERROR_MESSAGE = BaseFieldName.ERROR_MESSAGE.value
    MESSAGE = BaseFieldName.MESSAGE.value
    UNKNOWN_ANSWER = BaseFieldName.UNKNOWN_ANSWER.value

    SUCCESS = BaseFieldName.SUCCESS.value

    HELP = 6

    DEVICE_TYPE = 7
    PROTOCOL_VERSION = 8
    IS_RELEASE = 9
    ADDITIONAL_OPTIONS = 10

    INDEX = 11

    TRANSDUCER_ID = 12
    FREQUENCY = 13
    SWF = 14
    GAIN = 15
    TEMPERATURE = 16
    SIGNAL = 17
    WAVEFORM = 18
    URMS = 19
    IRMS = 20
    PHASE = 21
    TS_FLAG = 22
    PROCEDURE = 23
    PROCEDURE_ARG = 24
    ERROR_CODE = 25
    PASSWORD_HASHED = 26
    ANOMALY_DETECTION = 27
    VOLTAGE = 28
    TRANSDUCER_STATE = 29
    SYSTEM_STATE = 30

    TIMING = 31

    ATF = 32
    ATK = 33
    ATT = 34
    ATON = 35

    BUILD_DATE = 36
    BUILD_HASH = 37
    HARDWARE_VERSION = 38
    FIRMWARE_VERSION = 39
    SNR = 40

    CONTROL_MODE = 41
    COMM_MODE = 42
    COMMUNICATION_CHANNEL = 43
    COMMUNICATION_PROTOCOL = 44
    TERMINATION = 45

    TIMESTAMP = 46

    SCAN_F_CENTER = 47
    SCAN_F_RANGE = 48
    SCAN_F_STEP = 49
    SCAN_F_SHIFT = 50
    SCAN_T_STEP = 51
    SCAN_GAIN = 52
    TUNE_F_STEP = 53
    TUNE_F_SHIFT = 54
    TUNE_T_TIME = 55
    TUNE_T_STEP = 56
    TUNE_N_STEPS = 57
    TUNE_GAIN = 58
    WIPE_F_RANGE = 59
    WIPE_F_STEP = 60
    WIPE_T_ON = 61
    WIPE_T_OFF = 62
    WIPE_T_PAUSE = 63
    WIPE_GAIN = 64
    RAMP_F_START = 65
    RAMP_F_STOP = 66
    RAMP_F_STEP = 67
    RAMP_T_ON = 68
    RAMP_T_OFF = 69
    DUTY_CYCLE_T_OFF = 70
    DUTY_CYCLE_T_ON = 71

    LOG_LEVEL = 72
    LOGGER_NAME = 73

    # Legacy Fields
    LEGACY_RANG = 74
    LEGACY_STEP = 75
    LEGACY_SING = 76
    LEGACY_PAUS = 77
    LEGACY_TUST = 78
    LEGACY_TUTM = 79
    LEGACY_SCST = 80
    LEGACY_F_CENTER = 81
    LEGACY_POLL = 82

    MODBUS_SERVER_ID = 83

    DEVICE_STATE = 84

    MINUTES = 85
    HOURS = 86
    DAYS = 87

    RAMP_GAIN = 88
