changelog:
  exclude:
    labels:
      - documentation
      - test
      - duplicate
  categories:
    - title: New Features 🎉
      labels:
        - enhancement
    - title: Changes 🛠
      labels:
        - feature
    - title: Bug Fixes 🐞
      labels:
        - bug
