name: Build and Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: |
          '**/requirements.txt'
          '**/requirements-dev.txt'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install -r requirements.txt
        pip install -r requirements_dev.txt
  
    - name: Run build script
      run: call ./scripts/create_exe.bat ${{ github.workspace }}
      shell: cmd

    - name: Compile .ISS to .EXE Installer
      uses: Minionguyjpro/Inno-Setup-Action@v1.2.4
      with:
        path: scripts/installer.iss

    - name: Upload windows executable
      uses: actions/upload-artifact@v4
      with:
        name: windows executable
        path: ./dist/SonicControl/SonicControl.exe

    - name: Upload installer
      uses: actions/upload-artifact@v4
      with:
        name: windows installer
        path: ./dist/SonicControlInstaller/SonicControlInstaller.exe
