name: Build and Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_dev.txt
  
    - name: Run build script
      run: bash ./scripts/create_exe.sh ${{ github.workspace }}

    - name: Debug shit
      run: tree

    - name: Compile .ISS to .EXE Installer
      uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
      with:
        path: scripts/installer.iss

    - name: Upload windows executable
      uses: actions/upload-artifact@v2
      with:
        name: windows executable
        path: ./build/SonicControl/SonicControl.exe

    - name: Upload installer
      uses: actions/upload-artifact@v2
      with:
        name: windows installer
        path: ./build/SonicControlInstaller/SonicControlInstaller.exe
