name: Run unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

    
jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
    
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -e .

  unit_tests:
    runs-on: ubuntu-latest

    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Run PyTest
        run: python -m pytest
  

  system_tests:
    runs-on: ubuntu-latest

    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Run Robot
        run: python -m robot . -d ./results

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: results
      
