name: Run unit tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

    
jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: |
            '**/requirements.txt'
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Upload cache
        uses: actions/upload-artifact@v4
        with:
          name: python-cache
          path: ~/.cache/pip


  unit_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Download cache
        uses: actions/download-artifact@v4
        with:
          name: python-cache
          path: ~/.cache/pip

      - name: Run PyTest
        run: |
          pytest
  

  system_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Download cache
        uses: actions/download-artifact@v4
        with:
          name: python-cache
          path: ~/.cache/pip

      - name: Run Robot
        run: /
          robot . -d ./results

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: results
      
