name: Update Latest Tag

on:
  release:
    types: [published]

jobs:
  update-latest-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Fetch all tags and history
        run: git fetch --prune --unshallow --tags

      - name: Create or move 'latest' tag to the current release
        run: |
          git tag -fa latest -m "Update latest tag to release ${{ github.event.release.tag_name }}"
          git push origin latest --force
